# Generated by Django 5.0.6 on 2026-07-12 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Asset Manager', 'Asset Manager'), ('Department Head', 'Department Head'), ('Employee', 'Employee')], default='Employee', max_length=30)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myappp.department')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
