# Generated by Django 5.0.6 on 2026-07-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('ASSET_MANAGER', 'Asset Manager'), ('DEPARTMENT_HEAD', 'Department Head'), ('EMPLOYEE', 'Employee')], max_length=30)),
                ('otp', models.IntegerField(default=1234)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
