# Generated by Django 6.0.6 on 2026-07-12 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0007_asset_assetallocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_image',
        ),
    ]
