# Generated by Django 6.0.6 on 2026-07-12 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0009_assetrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_requests', to='myappp.employee'),
        ),
    ]
